package com.mock.msg.model;

// Generated May 18, 2015 9:42:35 AM by Hibernate Tools 4.3.1

/**
 * Follow generated by hbm2java
 * ALL hibernate tables should have a primary key, 
 * this table does not enforce uniqueness 
 */
public class Follow implements java.io.Serializable {

	private FollowId id;
	private User userByFollowId;
	private User userByUserId;

	public Follow() {
	}

	public Follow(FollowId id, User userByFollowId, User userByUserId) {
		this.id = id;
		this.userByFollowId = userByFollowId;
		this.userByUserId = userByUserId;
	}

	public FollowId getId() {
		return this.id;
	}

	public void setId(FollowId id) {
		this.id = id;
	}

	public User getUserByFollowId() {
		return this.userByFollowId;
	}

	public void setUserByFollowId(User userByFollowId) {
		this.userByFollowId = userByFollowId;
	}

	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

}
