package com.mock.msg.model;

// Generated May 18, 2015 9:42:35 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Tell generated by hbm2java
 */
public class Tell implements java.io.Serializable {

	private Integer tellId;
	private User user;
	private String message;
	private Date date;

	public Tell() {
	}

	public Tell(User user, Date date) {
		this.user = user;
		this.date = date;
	}

	public Tell(User user, String message, Date date) {
		this.user = user;
		this.message = message;
		this.date = date;
	}

	public Integer getTellId() {
		return this.tellId;
	}

	public void setTellId(Integer tellId) {
		this.tellId = tellId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
