package com.mock.msg.model;

// Generated May 18, 2015 9:42:35 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String name;
	private String password;
	private Set followsForFollowId = new HashSet(0);
	private Set followsForUserId = new HashSet(0);
	private Set tells = new HashSet(0);

	public User() {
	}

	public User(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public User(String name, String password, Set followsForFollowId,
			Set followsForUserId, Set tells) {
		this.name = name;
		this.password = password;
		this.followsForFollowId = followsForFollowId;
		this.followsForUserId = followsForUserId;
		this.tells = tells;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getFollowsForFollowId() {
		return this.followsForFollowId;
	}

	public void setFollowsForFollowId(Set followsForFollowId) {
		this.followsForFollowId = followsForFollowId;
	}

	public Set getFollowsForUserId() {
		return this.followsForUserId;
	}

	public void setFollowsForUserId(Set followsForUserId) {
		this.followsForUserId = followsForUserId;
	}

	public Set getTells() {
		return this.tells;
	}

	public void setTells(Set tells) {
		this.tells = tells;
	}

}
